package formmodelertest;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Child")
public class Child  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Integer ch_integer;
    
    @org.kie.api.definition.type.Position(value = 0)
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "ch_str")
    private java.lang.String ch_str;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Long ch_long;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "ch_bigInt")
    @org.kie.api.definition.type.Position(value = 2)
    private java.math.BigInteger ch_bigInt;
    
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.String ch_email;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.Short ch_short;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Float ch_float;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "ch_date")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.Date ch_date;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "ch_bigDec")
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigDecimal ch_bigDec;
    
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.String ch_longText;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "ch_boolean")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Boolean ch_boolean;
    
    @org.kie.api.definition.type.Position(value = 12)
    private java.util.Date ch_shortDate;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Double ch_double;

    public Child() {
    }

    public Child(java.lang.String ch_str, java.math.BigDecimal ch_bigDec, java.math.BigInteger ch_bigInt, java.lang.Boolean ch_boolean, java.util.Date ch_date, java.lang.Double ch_double, java.lang.Float ch_float, java.lang.Integer ch_integer, java.lang.Long ch_long, java.lang.Short ch_short, java.lang.String ch_email, java.lang.String ch_longText, java.util.Date ch_shortDate) {
        this.ch_str = ch_str;
        this.ch_bigDec = ch_bigDec;
        this.ch_bigInt = ch_bigInt;
        this.ch_boolean = ch_boolean;
        this.ch_date = ch_date;
        this.ch_double = ch_double;
        this.ch_float = ch_float;
        this.ch_integer = ch_integer;
        this.ch_long = ch_long;
        this.ch_short = ch_short;
        this.ch_email = ch_email;
        this.ch_longText = ch_longText;
        this.ch_shortDate = ch_shortDate;
    }


    
    public java.lang.Integer getCh_integer() {
        return this.ch_integer;
    }

    public void setCh_integer(  java.lang.Integer ch_integer ) {
        this.ch_integer = ch_integer;
    }
    
    public java.lang.String getCh_str() {
        return this.ch_str;
    }

    public void setCh_str(  java.lang.String ch_str ) {
        this.ch_str = ch_str;
    }
    
    public java.lang.Long getCh_long() {
        return this.ch_long;
    }

    public void setCh_long(  java.lang.Long ch_long ) {
        this.ch_long = ch_long;
    }
    
    public java.math.BigInteger getCh_bigInt() {
        return this.ch_bigInt;
    }

    public void setCh_bigInt(  java.math.BigInteger ch_bigInt ) {
        this.ch_bigInt = ch_bigInt;
    }
    
    public java.lang.String getCh_email() {
        return this.ch_email;
    }

    public void setCh_email(  java.lang.String ch_email ) {
        this.ch_email = ch_email;
    }
    
    public java.lang.Short getCh_short() {
        return this.ch_short;
    }

    public void setCh_short(  java.lang.Short ch_short ) {
        this.ch_short = ch_short;
    }
    
    public java.lang.Float getCh_float() {
        return this.ch_float;
    }

    public void setCh_float(  java.lang.Float ch_float ) {
        this.ch_float = ch_float;
    }
    
    public java.util.Date getCh_date() {
        return this.ch_date;
    }

    public void setCh_date(  java.util.Date ch_date ) {
        this.ch_date = ch_date;
    }
    
    public java.math.BigDecimal getCh_bigDec() {
        return this.ch_bigDec;
    }

    public void setCh_bigDec(  java.math.BigDecimal ch_bigDec ) {
        this.ch_bigDec = ch_bigDec;
    }
    
    public java.lang.String getCh_longText() {
        return this.ch_longText;
    }

    public void setCh_longText(  java.lang.String ch_longText ) {
        this.ch_longText = ch_longText;
    }
    
    public java.lang.Boolean getCh_boolean() {
        return this.ch_boolean;
    }

    public void setCh_boolean(  java.lang.Boolean ch_boolean ) {
        this.ch_boolean = ch_boolean;
    }
    
    public java.util.Date getCh_shortDate() {
        return this.ch_shortDate;
    }

    public void setCh_shortDate(  java.util.Date ch_shortDate ) {
        this.ch_shortDate = ch_shortDate;
    }
    
    public java.lang.Double getCh_double() {
        return this.ch_double;
    }

    public void setCh_double(  java.lang.Double ch_double ) {
        this.ch_double = ch_double;
    }




}