package formmodelertest;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Father")
public class Father  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Boolean f_boolean;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.Date f_date;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigInteger f_bigInteger;
    
    @org.kie.api.definition.type.Position(value = 12)
    private formmodelertest.Child simple_child2;
    
    @org.kie.api.definition.type.Position(value = 10)
    private formmodelertest.Child simple_child1;
    
    @org.kie.api.definition.type.Position(value = 14)
    private java.lang.String f_email;
    
    @org.kie.api.definition.type.Position(value = 13)
    private java.util.List<formmodelertest.Child> childs2;
    
    @org.kie.api.definition.type.Position(value = 11)
    private java.util.List<formmodelertest.Child> childs1;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Double f_double;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String f_string;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Short f_short;
    
    @org.kie.api.definition.type.Position(value = 17)
    private java.lang.String f_htmlEditor;
    
    @org.kie.api.definition.type.Position(value = 15)
    private java.lang.String f_longText;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Integer f_integer;
    
    @org.kie.api.definition.type.Position(value = 16)
    private java.util.Date f_shortDate;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Long f_long;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Float f_float;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.math.BigDecimal f_bigDecimal;

    public Father() {
    }

    public Father(java.math.BigDecimal f_bigDecimal, java.math.BigInteger f_bigInteger, java.lang.Boolean f_boolean, java.util.Date f_date, java.lang.Double f_double, java.lang.Float f_float, java.lang.Integer f_integer, java.lang.Long f_long, java.lang.Short f_short, java.lang.String f_string, formmodelertest.Child simple_child1, java.util.List<formmodelertest.Child> childs1, formmodelertest.Child simple_child2, java.util.List<formmodelertest.Child> childs2, java.lang.String f_email, java.lang.String f_longText, java.util.Date f_shortDate, java.lang.String f_htmlEditor) {
        this.f_bigDecimal = f_bigDecimal;
        this.f_bigInteger = f_bigInteger;
        this.f_boolean = f_boolean;
        this.f_date = f_date;
        this.f_double = f_double;
        this.f_float = f_float;
        this.f_integer = f_integer;
        this.f_long = f_long;
        this.f_short = f_short;
        this.f_string = f_string;
        this.simple_child1 = simple_child1;
        this.childs1 = childs1;
        this.simple_child2 = simple_child2;
        this.childs2 = childs2;
        this.f_email = f_email;
        this.f_longText = f_longText;
        this.f_shortDate = f_shortDate;
        this.f_htmlEditor = f_htmlEditor;
    }


    
    public java.lang.Boolean getF_boolean() {
        return this.f_boolean;
    }

    public void setF_boolean(  java.lang.Boolean f_boolean ) {
        this.f_boolean = f_boolean;
    }
    
    public java.util.Date getF_date() {
        return this.f_date;
    }

    public void setF_date(  java.util.Date f_date ) {
        this.f_date = f_date;
    }
    
    public java.math.BigInteger getF_bigInteger() {
        return this.f_bigInteger;
    }

    public void setF_bigInteger(  java.math.BigInteger f_bigInteger ) {
        this.f_bigInteger = f_bigInteger;
    }
    
    public formmodelertest.Child getSimple_child2() {
        return this.simple_child2;
    }

    public void setSimple_child2(  formmodelertest.Child simple_child2 ) {
        this.simple_child2 = simple_child2;
    }
    
    public formmodelertest.Child getSimple_child1() {
        return this.simple_child1;
    }

    public void setSimple_child1(  formmodelertest.Child simple_child1 ) {
        this.simple_child1 = simple_child1;
    }
    
    public java.lang.String getF_email() {
        return this.f_email;
    }

    public void setF_email(  java.lang.String f_email ) {
        this.f_email = f_email;
    }
    
    public java.util.List<formmodelertest.Child> getChilds2() {
        return this.childs2;
    }

    public void setChilds2(  java.util.List<formmodelertest.Child> childs2 ) {
        this.childs2 = childs2;
    }
    
    public java.util.List<formmodelertest.Child> getChilds1() {
        return this.childs1;
    }

    public void setChilds1(  java.util.List<formmodelertest.Child> childs1 ) {
        this.childs1 = childs1;
    }
    
    public java.lang.Double getF_double() {
        return this.f_double;
    }

    public void setF_double(  java.lang.Double f_double ) {
        this.f_double = f_double;
    }
    
    public java.lang.String getF_string() {
        return this.f_string;
    }

    public void setF_string(  java.lang.String f_string ) {
        this.f_string = f_string;
    }
    
    public java.lang.Short getF_short() {
        return this.f_short;
    }

    public void setF_short(  java.lang.Short f_short ) {
        this.f_short = f_short;
    }
    
    public java.lang.String getF_htmlEditor() {
        return this.f_htmlEditor;
    }

    public void setF_htmlEditor(  java.lang.String f_htmlEditor ) {
        this.f_htmlEditor = f_htmlEditor;
    }
    
    public java.lang.String getF_longText() {
        return this.f_longText;
    }

    public void setF_longText(  java.lang.String f_longText ) {
        this.f_longText = f_longText;
    }
    
    public java.lang.Integer getF_integer() {
        return this.f_integer;
    }

    public void setF_integer(  java.lang.Integer f_integer ) {
        this.f_integer = f_integer;
    }
    
    public java.util.Date getF_shortDate() {
        return this.f_shortDate;
    }

    public void setF_shortDate(  java.util.Date f_shortDate ) {
        this.f_shortDate = f_shortDate;
    }
    
    public java.lang.Long getF_long() {
        return this.f_long;
    }

    public void setF_long(  java.lang.Long f_long ) {
        this.f_long = f_long;
    }
    
    public java.lang.Float getF_float() {
        return this.f_float;
    }

    public void setF_float(  java.lang.Float f_float ) {
        this.f_float = f_float;
    }
    
    public java.math.BigDecimal getF_bigDecimal() {
        return this.f_bigDecimal;
    }

    public void setF_bigDecimal(  java.math.BigDecimal f_bigDecimal ) {
        this.f_bigDecimal = f_bigDecimal;
    }




}