package formmodelertest;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class TestChild  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.math.BigDecimal bigDecimal1;
    
    @org.kie.api.definition.type.Position(value = 16)
    private java.lang.Float float2;
    
    @org.kie.api.definition.type.Position(value = 18)
    private java.lang.Integer integer1;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.math.BigInteger bigInteger1;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.math.BigDecimal bigDecimal2;
    
    @org.kie.api.definition.type.Position(value = 17)
    private java.lang.Float float3;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.math.BigDecimal bigDecimal3;
    
    @org.kie.api.definition.type.Position(value = 15)
    private java.lang.Float float1;
    
    @org.kie.api.definition.type.Position(value = 28)
    private java.lang.String string2;
    
    @org.kie.api.definition.type.Position(value = 27)
    private java.lang.String string1;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.math.BigInteger bigInteger2;
    
    @org.kie.api.definition.type.Position(value = 20)
    private java.lang.Integer integer3;
    
    @org.kie.api.definition.type.Position(value = 29)
    private java.lang.String string3;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.math.BigInteger bigInteger3;
    
    @org.kie.api.definition.type.Position(value = 19)
    private java.lang.Integer integer2;
    
    @org.kie.api.definition.type.Position(value = 23)
    private java.lang.Long long3;
    
    @org.kie.api.definition.type.Position(value = 22)
    private java.lang.Long long2;
    
    @org.kie.api.definition.type.Position(value = 21)
    private java.lang.Long long1;
    
    @org.kie.api.definition.type.Position(value = 11)
    private java.util.Date date3;
    
    @org.kie.api.definition.type.Position(value = 10)
    private java.util.Date date2;
    
    @org.kie.api.definition.type.Position(value = 12)
    private java.lang.Double double1;
    
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.Double double2;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.util.Date date1;
    
    @org.kie.api.definition.type.Position(value = 14)
    private java.lang.Double double3;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.Boolean boolean3;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.Boolean boolean2;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Boolean boolean1;
    
    @org.kie.api.definition.type.Position(value = 25)
    private java.lang.Short short2;
    
    @org.kie.api.definition.type.Position(value = 26)
    private java.lang.Short short3;
    
    @org.kie.api.definition.type.Position(value = 24)
    private java.lang.Short short1;

    public TestChild() {
    }

    public TestChild(java.math.BigDecimal bigDecimal1, java.math.BigDecimal bigDecimal2, java.math.BigDecimal bigDecimal3, java.math.BigInteger bigInteger1, java.math.BigInteger bigInteger2, java.math.BigInteger bigInteger3, java.lang.Boolean boolean1, java.lang.Boolean boolean2, java.lang.Boolean boolean3, java.util.Date date1, java.util.Date date2, java.util.Date date3, java.lang.Double double1, java.lang.Double double2, java.lang.Double double3, java.lang.Float float1, java.lang.Float float2, java.lang.Float float3, java.lang.Integer integer1, java.lang.Integer integer2, java.lang.Integer integer3, java.lang.Long long1, java.lang.Long long2, java.lang.Long long3, java.lang.Short short1, java.lang.Short short2, java.lang.Short short3, java.lang.String string1, java.lang.String string2, java.lang.String string3) {
        this.bigDecimal1 = bigDecimal1;
        this.bigDecimal2 = bigDecimal2;
        this.bigDecimal3 = bigDecimal3;
        this.bigInteger1 = bigInteger1;
        this.bigInteger2 = bigInteger2;
        this.bigInteger3 = bigInteger3;
        this.boolean1 = boolean1;
        this.boolean2 = boolean2;
        this.boolean3 = boolean3;
        this.date1 = date1;
        this.date2 = date2;
        this.date3 = date3;
        this.double1 = double1;
        this.double2 = double2;
        this.double3 = double3;
        this.float1 = float1;
        this.float2 = float2;
        this.float3 = float3;
        this.integer1 = integer1;
        this.integer2 = integer2;
        this.integer3 = integer3;
        this.long1 = long1;
        this.long2 = long2;
        this.long3 = long3;
        this.short1 = short1;
        this.short2 = short2;
        this.short3 = short3;
        this.string1 = string1;
        this.string2 = string2;
        this.string3 = string3;
    }


    
    public java.math.BigDecimal getBigDecimal1() {
        return this.bigDecimal1;
    }

    public void setBigDecimal1(  java.math.BigDecimal bigDecimal1 ) {
        this.bigDecimal1 = bigDecimal1;
    }
    
    public java.lang.Float getFloat2() {
        return this.float2;
    }

    public void setFloat2(  java.lang.Float float2 ) {
        this.float2 = float2;
    }
    
    public java.lang.Integer getInteger1() {
        return this.integer1;
    }

    public void setInteger1(  java.lang.Integer integer1 ) {
        this.integer1 = integer1;
    }
    
    public java.math.BigInteger getBigInteger1() {
        return this.bigInteger1;
    }

    public void setBigInteger1(  java.math.BigInteger bigInteger1 ) {
        this.bigInteger1 = bigInteger1;
    }
    
    public java.math.BigDecimal getBigDecimal2() {
        return this.bigDecimal2;
    }

    public void setBigDecimal2(  java.math.BigDecimal bigDecimal2 ) {
        this.bigDecimal2 = bigDecimal2;
    }
    
    public java.lang.Float getFloat3() {
        return this.float3;
    }

    public void setFloat3(  java.lang.Float float3 ) {
        this.float3 = float3;
    }
    
    public java.math.BigDecimal getBigDecimal3() {
        return this.bigDecimal3;
    }

    public void setBigDecimal3(  java.math.BigDecimal bigDecimal3 ) {
        this.bigDecimal3 = bigDecimal3;
    }
    
    public java.lang.Float getFloat1() {
        return this.float1;
    }

    public void setFloat1(  java.lang.Float float1 ) {
        this.float1 = float1;
    }
    
    public java.lang.String getString2() {
        return this.string2;
    }

    public void setString2(  java.lang.String string2 ) {
        this.string2 = string2;
    }
    
    public java.lang.String getString1() {
        return this.string1;
    }

    public void setString1(  java.lang.String string1 ) {
        this.string1 = string1;
    }
    
    public java.math.BigInteger getBigInteger2() {
        return this.bigInteger2;
    }

    public void setBigInteger2(  java.math.BigInteger bigInteger2 ) {
        this.bigInteger2 = bigInteger2;
    }
    
    public java.lang.Integer getInteger3() {
        return this.integer3;
    }

    public void setInteger3(  java.lang.Integer integer3 ) {
        this.integer3 = integer3;
    }
    
    public java.lang.String getString3() {
        return this.string3;
    }

    public void setString3(  java.lang.String string3 ) {
        this.string3 = string3;
    }
    
    public java.math.BigInteger getBigInteger3() {
        return this.bigInteger3;
    }

    public void setBigInteger3(  java.math.BigInteger bigInteger3 ) {
        this.bigInteger3 = bigInteger3;
    }
    
    public java.lang.Integer getInteger2() {
        return this.integer2;
    }

    public void setInteger2(  java.lang.Integer integer2 ) {
        this.integer2 = integer2;
    }
    
    public java.lang.Long getLong3() {
        return this.long3;
    }

    public void setLong3(  java.lang.Long long3 ) {
        this.long3 = long3;
    }
    
    public java.lang.Long getLong2() {
        return this.long2;
    }

    public void setLong2(  java.lang.Long long2 ) {
        this.long2 = long2;
    }
    
    public java.lang.Long getLong1() {
        return this.long1;
    }

    public void setLong1(  java.lang.Long long1 ) {
        this.long1 = long1;
    }
    
    public java.util.Date getDate3() {
        return this.date3;
    }

    public void setDate3(  java.util.Date date3 ) {
        this.date3 = date3;
    }
    
    public java.util.Date getDate2() {
        return this.date2;
    }

    public void setDate2(  java.util.Date date2 ) {
        this.date2 = date2;
    }
    
    public java.lang.Double getDouble1() {
        return this.double1;
    }

    public void setDouble1(  java.lang.Double double1 ) {
        this.double1 = double1;
    }
    
    public java.lang.Double getDouble2() {
        return this.double2;
    }

    public void setDouble2(  java.lang.Double double2 ) {
        this.double2 = double2;
    }
    
    public java.util.Date getDate1() {
        return this.date1;
    }

    public void setDate1(  java.util.Date date1 ) {
        this.date1 = date1;
    }
    
    public java.lang.Double getDouble3() {
        return this.double3;
    }

    public void setDouble3(  java.lang.Double double3 ) {
        this.double3 = double3;
    }
    
    public java.lang.Boolean getBoolean3() {
        return this.boolean3;
    }

    public void setBoolean3(  java.lang.Boolean boolean3 ) {
        this.boolean3 = boolean3;
    }
    
    public java.lang.Boolean getBoolean2() {
        return this.boolean2;
    }

    public void setBoolean2(  java.lang.Boolean boolean2 ) {
        this.boolean2 = boolean2;
    }
    
    public java.lang.Boolean getBoolean1() {
        return this.boolean1;
    }

    public void setBoolean1(  java.lang.Boolean boolean1 ) {
        this.boolean1 = boolean1;
    }
    
    public java.lang.Short getShort2() {
        return this.short2;
    }

    public void setShort2(  java.lang.Short short2 ) {
        this.short2 = short2;
    }
    
    public java.lang.Short getShort3() {
        return this.short3;
    }

    public void setShort3(  java.lang.Short short3 ) {
        this.short3 = short3;
    }
    
    public java.lang.Short getShort1() {
        return this.short1;
    }

    public void setShort1(  java.lang.Short short1 ) {
        this.short1 = short1;
    }




}