package testform;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Line")
public class Line  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String c_1;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String c_2;

    public Line() {
    }

    public Line(java.lang.String c_1, java.lang.String c_2) {
        this.c_1 = c_1;
        this.c_2 = c_2;
    }


    
    public java.lang.String getC_1() {
        return this.c_1;
    }

    public void setC_1(  java.lang.String c_1 ) {
        this.c_1 = c_1;
    }
    
    public java.lang.String getC_2() {
        return this.c_2;
    }

    public void setC_2(  java.lang.String c_2 ) {
        this.c_2 = c_2;
    }
}