package guvnor.example2;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Shape  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private String shapeName;

    public Shape() {
    }

    public Shape(String shapeName) {
        this.shapeName = shapeName;
    }


    
    public String getShapeName() {
        return this.shapeName;
    }

    public void setShapeName(  String shapeName ) {
        this.shapeName = shapeName;
    }
}