package guvnor.example2;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Shape  implements java.io.Serializable {

static final long serialVersionUID = 1L;

    public Shape() {
    }




}